import { useTheme } from "@mui/material/styles";
import { Box } from "@mui/system";
import Head from "next/head";
import Image from "next/image";
import React, { useEffect } from "react";
import { ColorContext } from "../contexts/ColorContext";
import styles from "../styles/Home.module.css";
import Header from "./src/components/Header";
import instance from "../config";
import PrivateRoute from "./src/routes/PrivateRoute";
import { BrowserRouter } from "react-router-dom";
import HomePage from "./src/views/HomePage";

// export default function index() {
//   return (
//     <div>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <Box>
//         <BrowserRouter history={history}>
//           <PrivateRoute />
//         </BrowserRouter>
//       </Box>
//     </div>
//   );
// }

const Index = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <HomePage />
    </main>
  </div>
);

export default Index;
